name: Auto Commit and Push

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *"  # Runs every hour (adjust as needed)
  workflow_dispatch:  # Allows manual triggering of the workflow

permissions:
  contents: write  # ✅ Grants write access for pushing commits

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Prevents using default credentials

      - name: Set Up Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Authenticate with GitHub Token
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/codewithaswinkumar/SpringRequestBody.git

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Automated commit from GitHub Actions" || echo "No changes to commit"
          git push origin main
