name: CI/CD Pipeline for Java 8 Spring Boot

on:
  push:
    branches:
      - main  # Runs on push to the main branch
  pull_request:
    branches:
      - main  # Runs on pull requests to main

jobs:
  build:
    runs-on: ubuntu-latest  # Runs on a Linux server

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Gets the latest code from GitHub

      - name: Set Up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Eclipse Temurin (AdoptOpenJDK)
          java-version: '8'

      - name: Build and Test with Maven
        run: mvn clean install  # Builds the project and runs tests

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4  # Update to latest version
        with:
          name: spring-boot-app
          path: target/*.jar

  deploy:
    needs: build  # Runs only after the build job succeeds
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: spring-boot-app
          path: target/

      # OPTIONAL: Deploy to a Remote Server via SCP (Modify with your server details)
      # - name: Deploy to Server
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}   # Your server's IP address
      #     username: ${{ secrets.SERVER_USER }}  # SSH Username
      #     key: ${{ secrets.SERVER_SSH_KEY }}  # SSH Private Key stored as a GitHub Secret
      #     source: "target/*.jar"
      #     target: "/opt/myapp/"  # Deployment directory on the server
